### ISSUE TITLE
QuantumCircuit改成两位数会不会好点?

### ISSUE THREAD

**Issue by lionkingc** [yinfupai/LiuYaoForQuantum#1]
源码中是一位数, 摇三次, 再计算1的次数定动爻;
QuantumCircuit改成两位数会不会好点?
#00老阴
#01少阳
#10少阴
#11老阳

**Comment by yinfupai** [comment]
可以，不过免费资源有限，所以是考虑的是如何将尽量少的将资源进行重复使用
